apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent-service.fullname" . }}-config
data:
  APP_ENV: "production"
  REDIS_HOST: "{{ .Release.Name }}-redis-master"
  REDIS_PORT: "6379"
  OPENAI_MODEL: "gpt-4"
  MAX_TOKENS: "1000"