{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "agent-service.fullname" . }}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.istio.gateway.hosts | quote }}

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "agent-service.fullname" . }}-virtualservice
spec:
  hosts:
  - {{ .Values.istio.gateway.hosts | quote }}
  gateways:
  - {{ include "agent-service.fullname" . }}-gateway
  http:
  - route:
    - destination:
        host: {{ include "agent-service.fullname" . }}
        port:
          number: {{ .Values.service.port }}
{{- end }}