apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent-service.fullname" . }}-secrets
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.openai.apiKey | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | b64enc | quote }}
  AAD_CLIENT_SECRET: {{ .Values.azure.clientSecret | b64enc | quote }}