apiVersion: v2
name: agent-service
description: AI Agent Service with streaming support
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: redis
    version: 17.11.6
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: istio
    version: "1.18.2"
    repository: "https://istio-release.storage.googleapis.com/charts"
    condition: istio.install.enabled